disabled_rules:
  - force_cast
  - force_try
  - trailing_whitespace

line_length: 150

cyclomatic_complexity: 12

variable_name:
  max_length:
    warning: 50
    error: 70
  min_length:
    error: 1

identifier_name:
  excluded:
    - id

excluded:
  - Specs
  - Pods
