# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  
  before_all do
    puts "Doin' some fastlane..."
  end
  
  desc "Builds and SwiftLints the workspace"
  lane :build do
    xcodebuild(scheme: <ENTER YOUR SCHEME HERE>,
               workspace: "<ENTER YOUR MODULE NAME HERE>.xcworkspace",
               xcpretty_output: "rspec")

   swiftlint(strict: true,
             quiet: true,
             config_file: ".swiftlint.yml",
             executable: "Pods/SwiftLint/swiftlint")
  end

  desc "Runs the specs"
  lane :specs do
    swiftlint(strict: true,
              quiet: true,
              config_file: ".swiftlint.yml",
              executable: "Pods/SwiftLint/swiftlint")
    
    scan(scheme: <ENTER YOUR SCHEME HERE>,
         output_style: "rspec")
  end
  
  desc "Install Carthage dependencies"
  lane :carthage_install do
    carthage(command: "update",
             platform: "ios")
  end

  desc "Builds <ENTER YOUR MODULE NAME HERE>.framework.zip using Carthage"
  lane :build_carthage_framework do
    carthage(command: "build",
             no_skip_current: true)

    carthage(command: "archive")
  end

  desc "Builds <ENTER YOUR MODULE NAME HERE> using SPM"
  lane :build_spm do
    spm
  end

  after_all do |lane|
      puts "🌮 🌮 🌮  Taco Time! 🌮 🌮 🌮"
  end

  error do |lane, exception|
    puts "uh oh...."
  end

end
